### ISSUE TITLE
Problem with Griffin Stat extraction from Ragnarok map

### ISSUE THREAD

**Issue by doriath** [cadon/ARKStatsExtractor#401] opened 2017-07-22 23:17 UTC
I am running on my custom multiplayer server (but only the taming speed has been adjusted to x2) on Ragnarok map, and I can't extract stats for Griffin. Here is a screenshot:

![timon](https://user-images.githubusercontent.com/150959/28495130-66639d2e-6f12-11e7-87d7-1d034376111e.jpg)

**Comment by cadon** [comment] 2017-08-13 19:48
Hi, I finally found the issue. The issue is resolved in the newest version (0.23.14).

**Closed by cadon** 2017-08-13 19:48 UTC
Labels: stat-issue
