### ISSUE TITLE
Tek Rex imported from map data as Abberrant Paracer's

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#731] opened 2018-07-01 15:51 UTC
So I am breeding my Tek Rex's and went and imported them into the current latest version of this program, problem is that they come in as Aberrant Paracer's

**Comment by VolatilePulse** [comment] 2018-07-01 17:01
We are currently experiencing similar issues when the "Last Exported" button is being used. Users have mentioned that using the "Import Exported Data" button has been bypassing all importing issues. As the developer is currently on vacation, there won't be an immediate fix for a few days. The "Import Exported Data" feature provides a bit more versatility as well. Try this and let us know if the issues persist. Thanks!

**Comment by VolatilePulse** [comment] 2018-07-01 19:51
While admittedly it's been a while since I looked at the code, I believe the menu option and the button are linked to the same function and likely have the same issue. The limitation to either is that it can only do one creature at a time and are currently experiencing issues at the moment.

Aside from no known issues from using the "Import Exported Data" button, it offers the ability to import multiple species at once. This means you can export as many creatures as you want in Ark and then switch to ASB and import all of them at once. It even distinguishes and moves all previously imported creatures to the bottom of the list for easier viewing.

There is one known limitation, and it applies to "Last Export" as well, is that in order for ASB to be able to link the parents to the creature, all parents must have been imported, or added with the use of ark-tools, and the creatures "Show Ancestors" window been opened prior to exporting. This limitation exists due to an issue with Ark. I believe this is by design by the developers and as such may never be changed.

**Comment by cyberangel67** [comment] 2018-07-01 20:02
Do you mean export from Ark or Ark Tools? I am not aware of any export in Ark itself.

**Comment by VolatilePulse** [comment] 2018-07-01 21:06
Oh, by import do you mean importing the ark-tools output?

Ever since the 2nd TLC update, you've been able to export creature data. It's a completely different technique than using ark-tools, but since the ark-tools developer hasn't been active, this may be a better option. To export a creature, simply open the action wheel and select "Export Dino" I think is the correct wording. ASB supports importing from both ark-tools or Creature Export.

**Comment by VolatilePulse** [comment] 2018-07-02 06:09
The issue you're describing was supposedly fixed several updates ago. What version of ASB are you using? The latest is 0.28.6.1

**Comment by cyberangel67** [comment] 2018-07-02 06:41
I said what version in my initial ticket

**Comment by cyberangel67** [comment] 2018-07-19 10:31
Is there any news on a fix for this?

**Comment by cadon** [comment] 2018-07-19 20:41
Hi, that'll be fixed in the next release. The issue is, ark-tools does use different species-names, some have to be fixed manually like the `Tek Rex`, whereas ark-tools (and ARK internally) calls them `BionicRex`.

**Closed** 2018-07-22 17:33 UTC
Labels: bug
