### ISSUE TITLE
Imported dinosaurs without names cause unhandled exception

### ISSUE THREAD

**Issue by TheFeshy** [cadon/ARKStatsExtractor#847] opened 2018-12-08 16:58 UTC
When importing from a saved game, dinosaurs without a name will not have a name field in the saved xml file.  If at least two dinosaurs have no name tag, this will cause an unhandled exception (Function does not accept Not a Number) when sorting by  name - in fact, it will cause an exception for every dinosaur in the list, as it tries to sort.

Since sorting by name is the default, and the default selection is "all", this will cause an exception for every dinosaur in your file on startup if you have imported them.

Adding a blank name tag in the xml (e.g. <name></name> underneath the species tag) seems to prevent this error; unfortunately when the file is next saved it uses the proper <name /> tag, which causes the error again.

(Note: I have ARKStatsExtractor installed in wine under linux currently.)

**Comment by Flachdachs** [comment] 2018-12-09 09:51
I can't reproduce an exception. I can however see that the field is not written if the import assigns null to the name. I can set an empty string as the default value for the name field, if this fixes it.

**Comment by Flachdachs** [comment] 2018-12-22 20:41
Fixed in ca933f0

**Closed by Flachdachs** 2018-12-22 20:41 UTC
Labels: bug
