### ISSUE TITLE
values.json file download times out and Windows Defender blocks installer download/install

### ISSUE THREAD

**Issue by neostryder** [cadon/ARKStatsExtractor#1061] opened 2020-04-09 00:59 UTC
Updates failed, so I re-downloaded the app, however, I had to force it past Windows Defender.  You might want to submit to them whatever they need to validate it.  Also, shortly after launching, I get a popup saying that a new values.json file is available, then I click to retrieve it and it hangs the program for several minutes before timing out with the attached error.
![2020-04-08_17-56-55](https://user-images.githubusercontent.com/61663569/78847100-abbb0c00-79c2-11ea-91d4-0bff49c17188.png)

**Comment by VolatilePulse** [comment] 2020-04-09 01:47
An update was released just a few days ago that has corrected the false flag in Windows defender. In short, the issue was with the updater downloading the installer instead of the zip. We believe this issue has been resolved. As an added bonus, the updater should continue to work from version 0.39.3 and forward. If you do not currently have this version, you can get it from [here](https://github.com/cadon/ARKStatsExtractor/releases/latest).

As for the values file, it works fine for me and I have just verified the file exists. If you do not have the latest version of ASB, please download that first and try again. If you do, there may be a firewall or antivirus issue preventing ASB from contacting the internet. This is common when the program has been sandboxed and isn't allowed to do anything.

As for Defender flagging the updater, we have checked every antivirus software that we were capable of that flagged it. We believe the issue is directly related to how the updater was changed in 0.39.0 and was flagged as a malicious file because of it. All of the trojans the antivirus softwares flagged the updater as were based on heuristics and not confirmed by them. We are really sorry about the inconvenience this has caused and we believe this issue should be resolved.

The only pressing issue we are aware of is Windows prompting you to not run the program due to it not being signed. This issue is common amongst open source programs due to the fact that certificates are rather expensive and is not something that is likely to change for ASB since it is free software. 

If you have anymore concerns or issues, please let us know.

**Comment by VolatilePulse** [comment] 2020-04-10 03:52
I'm closing this since I just successfully updated the values file to a new version that has appeared since I replied and it work successfully. If you need further assistance with this issue, please reply with steps that you've taken so far and any additional information that might be helpful.

**Closed by VolatilePulse** 2020-04-10 03:52 UTC
Labels: bug, question
