### ISSUE TITLE
Genesis 2 Savegame won`t load.

### ISSUE THREAD

**Issue by DaRkVaMpiRe11** [cadon/ARKStatsExtractor#1231] opened 2021-09-19 22:53 UTC
Hello, since today, i can`t load my Gen2 Savegame, into Smart BReeding. 
I tried it direktly over FTP,,
or Downloaded the Ark Savegame, and loadet it.
Everytime i get the Same message.
My Other Savegames Work just Fine.
[Here is a Picture from the Error Window](https://ibb.co/0mrfyGk).
Thanks a Lot.

**Comment by cadon** [comment] 2021-09-20 18:33
Hi, that looks like a bug in the application. For further investigation the save file that causes the issue is needed. Make sure to compress it (e.g. .zip or .rar), then sending it via pm on discord would be good, you can find me (cadaei) on the [ASB-discord server](https://discord.gg/qCYYbQK).

**Comment by cadon** [comment] 2021-09-29 19:17
Fixed in https://github.com/cadon/ArkSavegameToolkit/commit/341c23572e635f3f934cba7ac3c4f3840bbe75ee

**Closed by cadon** 2021-09-29 19:17 UTC
Labels: bug
