### ISSUE TITLE
Giganoto Stats Calculation Incorrect?

### ISSUE THREAD

**Issue by ToTac** [cadon/ARKStatsExtractor#117] opened 2016-10-29 09:31 UTC
Hello there.
First of all: Thank you a lot for this awesome tool, it really helps me and my friends with our tames and makes our ingame lifes easier.

I stumpled over several stat calculation issues in the extractor, most of them were rather minor, others make it impossible to add newly tamed creatures of certain species with correct stats or at all.

My most recent problem is my newly tamed Giganotosaurus, that turned out level 162.

![giganoto_lvl162_tamed](https://cloud.githubusercontent.com/assets/23134973/19828506/5a14cbc8-9dc7-11e6-80e5-bf09b41d153e.jpg)

However the Extractor doesn't seem to be able to calculate the stats correctly.

![giganoto_lvl162_extractor](https://cloud.githubusercontent.com/assets/23134973/19828513/9e9035bc-9dc7-11e6-9a1b-5c00eb33a3e7.PNG)

TE isn't calculated (should be something around 95% because of the double taming rate event).
The wild level isn't calculated.
The Extractor always puts 130 or 131 points into Speed.

**Comment by cadon** [comment] 2016-11-29 23:20
Hi, sorry for the late reply. It could be that the TE cannot be determined for the Giganotosaurus because of the extreme (high and low) values it has. The Giganotosaurus got nerfed recently, maybe it works with the new values, if the TE is still not calculated, but the extraction seemed to work, then I'd just add it to the library with an unknown TE.

**Comment by cyberangel67** [comment] 2016-12-08 13:42
If it helps I spawned in a 150 and did a DoTame on mine to try this and it wont let me enter the stats.

Yes the server is boosted, yes it has the correct values as everything else I entered works.
![capture](https://cloud.githubusercontent.com/assets/1366816/21012069/6abf43da-bda8-11e6-8be1-5dde625568cf.PNG)

**Comment by cadon** [comment] 2016-12-10 19:20
I'll do some tests with the Giganotosaurus.

**Comment by cyberangel67** [comment] 2016-12-11 00:20
I don't know if this helps, but I am on the Xbox where the nerfs haven't come through to us as yet.

**Comment by cadon** [comment] 2017-01-31 22:01
I'll close this issue for now, assuming it was caused by different versions on pc and the consoles. Feel free to reopen if it happens again.

**Closed by cadon** 2017-01-31 22:01 UTC
Labels: stat-issue

**Comment by cyberangel67** [comment] 2017-01-31 23:48
Not sure if this is happening to anyone else, but as you can see from the screenshots it is not working right. The extractor doesn't even know what level it is, nor can it get the TE right. The Library, has no LW defined, because the extractor can't calculate it.

This was entered running version 254.2

![capture](https://cloud.githubusercontent.com/assets/1366816/22489462/c60aec24-e86b-11e6-84c1-b9b271fcb237.PNG)
![capture1](https://cloud.githubusercontent.com/assets/1366816/22489468/c88d6684-e86b-11e6-9e35-7ecb71e905be.PNG)

**Comment by cadon** [comment] 2017-02-01 22:30
Hi, it's not possible to extract the TE of a giganotosaur, because its values are not dependant on the TE (you can check that in the Tester). The wild-level is calculated with the TE, so that is not possible either.

**Comment by cyberangel67** [comment] 2017-02-02 01:52
I guess that explains why it does that then.
