### ISSUE TITLE
Pulmonoscorpius stat extraction

### ISSUE THREAD

**Issue by Caisu** [cadon/ARKStatsExtractor#2] opened 2015-12-01 15:11 UTC
There appears to be something wrong with the scorpion stats, specifically HP and potentially also damage. When I try to extract values for either of my scorpions the HP line is always red with 'n/a' in the fields. Damage has the same issue until I drop taming effectiveness to 0%-100% - I'm not 100% sure if the taming effectiveness values it ends up (<50%) are accurate but I can't say for sure that they're not considering where I tamed those scorpions! I'm happy to provide screenshots, stat lines etc or run tests for you, just tell me what! 

I'm going to go tame another scorpion or two and see if it's maybe that they were tamed before a game update that's messed them up or something. I checked the stats against the info on the wiki - they have a very awkward wild HP increase, but updating the stats file doesn't appear to fix them. I had this issue with both your v0.10 and v0.11, running ARK v225.4.

**Comment by cadon** [comment] 2015-12-01 16:45
Hi, sending the level and stats of the creature(s) or a screenshot of these would be great.
Scorpions got a nerf recently (which was only considered in 0.11 of the tool), but the increase per level stayed the same, resulting in the strange number you mentioned. I checked it with some scorpions and it worked yesterday, but could be that there are again rounding errors or other things I haven't considered yet.

**Comment by Caisu** [comment] 2015-12-01 17:40
Here are the stats of the two scorpions affected - the lv33 was tamed first, maybe 4+ major versions ago, and the lv29 was more recent, no more than 3 major versions ago. Do you know if the stats of existing scorpions were retroactively updated when they were nerfed? If not that would create a real muddle for you, with some levels applied under the old stats and some under the new...

![2015-12-01 1](https://cloud.githubusercontent.com/assets/16102713/11508496/118d36aa-9851-11e5-9ae7-0e0d867348bb.png)
![2015-12-01 2](https://cloud.githubusercontent.com/assets/16102713/11508498/1194dc7a-9851-11e5-8bc6-c2ca149f4e63.png)
![2015-12-01](https://cloud.githubusercontent.com/assets/16102713/11508497/118df3ba-9851-11e5-9573-429f09e29bfa.png)

Unrelated to this, but I've also noticed that dinos caught at lv1 will not have their values extracted properly until 1 wild level of torpor has been added to their stats. For example a Sabertooth I have with 500.5 torpor in the game needs to be entered into your program as 530.5 to get the correct stats extracted, otherwise the program has all the stat lines white with 'n/a' in the fields. I can add this as a separate bug if you'd rather, I didn't want to flood your inbox especially if this was something caught in the v0.11 update!

**Comment by Caisu** [comment] 2015-12-01 19:06
Just went and tamed some more scorpions, there are 3 here, all have had one level applied into HP and all were >90% taming effectiveness. Worth noting is the lv5 that shows the program erroring on HP and instead saying the level up was spent in Stamina, which is was not, however lowering the TE gives the correct Sta distribution but still errored HP. Likewise, the lv35 shows a level spent in dmg which was, again, in HP. The lv2 has extracted correctly though!

![2015-12-01 3](https://cloud.githubusercontent.com/assets/16102713/11510939/0e53a854-985e-11e5-8fc6-f5b462ccd6fa.png)
![2015-12-01 4](https://cloud.githubusercontent.com/assets/16102713/11510940/0e58d540-985e-11e5-9b0e-345baf5a14a2.png)
![2015-12-01 5](https://cloud.githubusercontent.com/assets/16102713/11510941/0e5c7984-985e-11e5-888c-379c2fba1142.png)
![2015-12-01 6](https://cloud.githubusercontent.com/assets/16102713/11510942/0e5d55c0-985e-11e5-8834-4fca7fcc902b.png)

**Comment by cadon** [comment] 2015-12-01 19:52
Thanks for the screenshots. It's strange. The health can be explained sometimes with an increase of 20%, sometimes with the 21,...%. The bug with the point mistakenly assigned to stamina is related to the fact that the tool doesn't find any valid combination for the health.
I wait for the new update 226 and try to figure out what value the scorpions now have. I hope the game does only calculate the spent level and not the absolute value, that would make the tool useless for creatures tamed in another stat-era.

I couldn't reproduce the error with a level 1 sabertooth. Both the unconcious wild one and the tamed one (both level 1) were correctly recognized by the tool with a torpor of 500 and 500.5 repectively. Can you send a screenshot of that stats too? Thanks for your feedback!

**Comment by Caisu** [comment] 2015-12-01 20:03
I just checked the sabertooth I was having trouble with, it appears to be working now so I guess that was something that got fixed in v0.11! Thanks for making the app and continuing to work on it, it's so useful!

Side note, I have a spreadsheet with all my dinos stats before and after extraction and some that I've recorded the stats when they were tamed/born, I was wondering if you'd like a copy to use for testing? I'm up to my 4th generation of breeding now so there's a good range of stats for several species.

**Comment by cadon** [comment] 2015-12-02 13:44
That spreadsheet would be nice to have.

For the scorpionstats there seems to be two ways of calculating it. I tried it with v226.1 multiple times and the increase in the wild was always 21.4285... %. The stats you send me worked with an increase of exact 20%. Did you tame them before v225 (I think that's the version they changed the stats)?

For now, you can add an alternative entry for the scorpions and try both when extracting the stats. Just replace the scorpion-entry in the stats.txt with

    Pulmonoscorpius1
    280,.214285714285714,0.27,0.5,0
    200,0.1,0.1,0,0
    150,0.1,0.1,0,0
    1500,0.1,0.1,0,0
    200,0.02,0.04,0,0
    15,0.05,0.1,.5,0.4
    1,0,0.025,1,0
    150,0.06,0,0.5,0
    Pulmonoscorpius2
    280,.2,0.27,0.5,0
    200,0.1,0.1,0,0
    150,0.1,0.1,0,0
    1500,0.1,0.1,0,0
    200,0.02,0.04,0,0
    15,0.05,0.1,.5,0.4
    1,0,0.025,1,0
    150,0.06,0,0.5,0

**Comment by Caisu** [comment] 2015-12-02 14:08
The first two I sent you were tamed in v224 at the latest, the higher level of the two was likely v223 or earlier. The second three were all tamed in v225.4. I'll go see if I can find some more to rule out it being something weird in my game now I'm updated to v226.1. 

Here is the link to the spreadsheet since it wouldn't let me upload it here:
https://www.dropbox.com/s/d0y24owp9e7q2p3/Ark%20SP%20Dino%20Log.xlsx?dl=0
I'm updating it as a tame/hatch more dinos. Let me know if it works ok, I've had some issues with Dropbox links before so I can put it somewhere else if need be.

**Comment by Caisu** [comment] 2015-12-02 17:42
I went scorpion hunting again for you, definitely v226.1, this was the result. These were both just caught but see how one extracts with the old stats and the other with the new? Screenshots show freshly caught with no levels applied and after the first level application into HP for both scorpions.


![2015-12-02 9](https://cloud.githubusercontent.com/assets/16102713/11538859/c37b89f0-991b-11e5-95d6-b2b2c5e76cec.png)
![2015-12-02 8](https://cloud.githubusercontent.com/assets/16102713/11538858/c37a66ce-991b-11e5-9d82-c56adee9fe98.png)
![2015-12-02 2](https://cloud.githubusercontent.com/assets/16102713/11538790/5f9a0bbe-991b-11e5-9231-e23c15d02407.png)
![2015-12-02 3](https://cloud.githubusercontent.com/assets/16102713/11538792/5fc99dc0-991b-11e5-9320-c74fbfbdd6f0.png)
![2015-12-02 4](https://cloud.githubusercontent.com/assets/16102713/11538793/5fcb0f2a-991b-11e5-8e22-23c81c319883.png)
![2015-12-02 5](https://cloud.githubusercontent.com/assets/16102713/11538794/5fccdf30-991b-11e5-9224-30218219af12.png)
![2015-12-02 6](https://cloud.githubusercontent.com/assets/16102713/11538795/5fd2aa64-991b-11e5-806f-9f095b9df54a.png)
![2015-12-02 7](https://cloud.githubusercontent.com/assets/16102713/11538791/5fb358bc-991b-11e5-88bf-2a4440a8e632.png)

**Comment by cadon** [comment] 2015-12-03 12:21
Thanks, that's strange. I think the best is to leave both scorpion-version as option in the tool until the scorpions are equally leveled up or a system is found how they choose how to level up.

**Closed** 2016-02-27 22:15 UTC
Labels: bug
