### ISSUE TITLE
BD Pegomastax babies failing torpor extractor

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#990] opened 2019-11-14 15:16 UTC
I bred some Pegomastax while having Better Dinos installed (with the .ini provided here), but the Torpor amount is not recognized. However; if I use the Stat Testing to see what their torpor should be according to ASB, I get the **exact same** value. In this case, it was a level 180 Pegomastax, thus 179 Torpor. Both the Pegomastax and the Stat Testing list it as being 352,7.

**Comment by cadon** [comment] 2019-11-14 15:54
Can you provide all the stat-values and server-multipliers?
It could be that it's a rounding issue. Does it work with `352.6` or `352.8`?

**Comment by VolatilePulse** [comment] 2019-11-15 02:00
If you haven't had issues with other species, it is likely a duplicate of #987 or an issue with the Better Dinos' mod's buffs.

**Comment by soepie7** [comment] 2019-11-15 12:19
I will try it with the Torpor being rounded up or down with 0.1, but then first I need to breed a new one.

**Comment by soepie7** [comment] 2019-11-15 14:22
Can confirm that lowering it with 0.1 helped, which then means that Ark, the Extractor, and Stat Tester round the numbers differently.

**Comment by cadon** [comment] 2019-11-15 21:36
Thanks for the feedback! Can you post the text in the export file? That could help to fine-tune the rounding issues.

**Comment by soepie7** [comment] 2019-11-18 23:24
What text? The stats they had? That would then be a total lvl of 180, so 179 torpor. This, according to stat tester and in-game gives 352,7 torpor, but unless I rounded to 352,6 it was seen as an invalid value.

**Comment by VolatilePulse** [comment] 2019-11-18 23:35
I believe he is referring to the creature export file. If you are manually entering the values, that wouldn't apply to you. However, it is recommended to use the export feature so ASB can export extra data. You can read more about that [here](https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures#ark-exports).

**Comment by soepie7** [comment] 2019-11-22 08:36
I didn't have the creature or export file anymore, but I still had it in an .asb file. The file attached here only contains that specific creature.

For configs, in case they are not attached to the .asb files; official server multipliers.

[ASB-save.zip](https://github.com/cadon/ARKStatsExtractor/files/3878617/ASB-save.zip)

**Comment by cadon** [comment] 2020-03-13 15:08
Thanks, the latest precision handling tweaks seem to have fixed that.

**Closed by cadon** 2020-03-13 15:08 UTC
Labels: stat-issue
