### ISSUE TITLE
Extract crash bug - 23.14

### ISSUE THREAD

**Issue by caesar-17** [cadon/ARKStatsExtractor#437] opened 2017-08-14 08:59 UTC
Program crashed while extracting values on an Argentavis.
Went back to 23.13, and extraction was successful, no issues.

Reproducible bug.

(Awesome work by the way, thank you Cadon) :)

![ark_breeding_error_2](https://user-images.githubusercontent.com/31001187/29264970-0c436520-8094-11e7-9952-f970f8a30f84.PNG)

**Comment by cadon** [comment] 2017-08-14 15:58
Hi, can't reproduce this. What are your multipliers?

**Comment by caesar-17** [comment] 2017-08-14 18:16
Here they are sir


[ServerSettings]
ServerCrosshair=True
RCONPort=32335
StructurePreventResourceRadiusMultiplier=1.000000
RaidDinoCharacterFoodDrainMultiplier=1.0
PvEDinoDecayPeriodMultiplier=1.0
KickIdlePlayersPeriod=3600
PerPlatformMaxStructuresMultiplier=10.0
AutoSavePeriodMinutes=15.0
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=4000
RCONServerGameLogBuffer=600
AllowHitMarkers=True
ServerPassword=sloths
ServerAdminPassword=Bgawd852
SpectatorPassword=oogabooga
RCONEnabled=True
AdminLogging=False
ActiveMods=566885854,639841665,701819573,719928795,722649005,723136013,731604991,793605978,821530042
TribeLogDestroyedEnemyStructures=False
ServerHardcore=False
ServerPVE=True
AllowCaveBuildingPvE=True
EnableExtraStructurePreventionVolumes=False
DifficultyOffset=1.0
NoTributeDownloads=False
PreventOfflinePvP=True
PreventOfflinePvPInterval=900
PreventTribeAlliances=False
PreventDiseases=False
NonPermanentDiseases=True
globalVoiceChat=False
proximityChat=False
alwaysNotifyPlayerLeft=True
alwaysNotifyPlayerJoined=True
ServerForceNoHud=False
AllowThirdPersonPlayer=True
ShowMapPlayerLocation=True
EnablePVPGamma=False
DisablePvEGamma=True
ShowFloatingDamageText=True
AllowFlyerCarryPVE=True
XPMultiplier=1.5
TamedDinoDamageMultiplier=1.0
TamedDinoResistanceMultiplier=1.0
AllowRaidDinoFeeding=True
DisableDinoDecayPvE=True
DisableImprintDinoBuff=False
AllowAnyoneBabyImprintCuddle=False
TamingSpeedMultiplier=3.0
HarvestAmountMultiplier=2.0
ResourcesRespawnPeriodMultiplier=0.8
NightTimeSpeedScale=1.5
PvPStructureDecay=False
NewMaxStructuresInRange=25000.0
MaxPlatformSaddleStructureLimit=65535
OverrideStructurePlatformPrevention=True
PvEAllowStructuresAtSupplyDrops=False
DisableStructureDecayPVE=True
PvEStructureDecayDestructionPeriod=0.0
AutoDestroyOldStructuresMultiplier=0.0
ForceAllStructureLocking=False
OnlyAutoDestroyCoreStructures=False
OnlyDecayUnsnappedCoreStructures=False
FastDecayUnsnappedCoreStructures=False
TheMaxStructuresInRange=25000.0
OxygenSwimSpeedStatMultiplier=1.0
PvPDinoDecay=False
AutoDestroyDecayedDinos=False
MaxPersonalTamedDinos=500.0
DestroyUnconnectedWaterPipes=False
AllowCrateSpawnsOnTopOfStructures=True
DayCycleSpeedScale=0.75
DayTimeSpeedScale=0.5
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
PreventUploadSurvivors=False
PreventUploadItems=False
PreventUploadDinos=False
TributeCharacterExpirationSeconds=1200000
TributeItemExpirationSeconds=1200000
TributeDinoExpirationSeconds=1200000
PreventSpawnAnimations=False

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.700000
FOVMultiplier=1.000000
GroundClutterDensity=1.000000
bFilmGrain=False
bMotionBlur=False
bUseDFAO=False
bUseSSAO=True
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
bLocalInventoryShowAllItems=False
bRemoteInventoryShowAllItems=False
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=1
ActiveLingeringWorldTiles=7
ClientNetQuality=3
LastServerSearchType=0
LastDLCTypeSearchType=-1
LastServerSearchHideFull=False
LastServerSearchProtected=False
HideItemTextOverlay=False
bDistanceFieldShadowing=True
LODScalar=1.000000
bToggleToTalk=False
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=False
bChatShowTribeName=True
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bSpectatorManualFloatingNames=False
bSuppressAdminIcon=False
bUseSimpleDistanceMovement=False
bDisableMeleeCameraSwingAnims=False
bHighQualityAnisotropicFiltering=False
bPreventInventoryOpeningSounds=False
bPreventItemCraftingSounds=False
bPreventHitMarkers=False
bPreventCrosshair=False
bPreventColorizedItemNames=False
bHighQualityLODs=False
bExtraLevelStreamingDistance=False
bEnableColorGrading=True
DOFSettingInterpTime=0.000000
bDisableBloom=False
bDisableLightShafts=False
LastPVESearchType=-1
bUseVSync=False
MacroCtrl0=
MacroCtrl1=
MacroCtrl2=
MacroCtrl3=
MacroCtrl4=
MacroCtrl5=
MacroCtrl6=
MacroCtrl7=
MacroCtrl8=
MacroCtrl9=
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3
sg.GroundClutterRadius=10000

[SessionSettings]
SessionName=RagnaBAWK
Port=7778
QueryPort=27015
MultiHome=

[/Script/Engine.GameSession]
MaxPlayers=70

[MultiHome]
MultiHome=False

[MessageOfTheDay]
Message=BGAWWWK
Duration=20

[/Game/PrimalEarth/CoreBlueprints/TestGameMode.TestGameMode_C]
bServerGameLogEnabled=True

[Ragnarok]
EnableDevelopmentZones=true

**Comment by caesar-17** [comment] 2017-08-14 18:19
![ark_breeding_multipliers](https://user-images.githubusercontent.com/31001187/29285175-6d962f4e-80e2-11e7-8839-9887cc06dec4.png)

**Comment by caesar-17** [comment] 2017-08-14 18:24
I dragged and dropped the GameUserSettings.ini file onto the window to save the settings.

[ServerSettings]
ServerCrosshair=True
RCONPort=
StructurePreventResourceRadiusMultiplier=1.000000
RaidDinoCharacterFoodDrainMultiplier=1.0
PvEDinoDecayPeriodMultiplier=1.0
KickIdlePlayersPeriod=3600
PerPlatformMaxStructuresMultiplier=10.0
AutoSavePeriodMinutes=15.0
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=4000
RCONServerGameLogBuffer=600
AllowHitMarkers=True
ServerPassword=sloths
ServerAdminPassword=Bgawd852
SpectatorPassword=oogabooga
RCONEnabled=True
AdminLogging=False
ActiveMods=566885854,639841665,701819573,719928795,722649005,723136013,731604991,793605978,821530042
TribeLogDestroyedEnemyStructures=False
ServerHardcore=False
ServerPVE=True
AllowCaveBuildingPvE=True
EnableExtraStructurePreventionVolumes=False
DifficultyOffset=1.0
NoTributeDownloads=False
PreventOfflinePvP=True
PreventOfflinePvPInterval=900
PreventTribeAlliances=False
PreventDiseases=False
NonPermanentDiseases=True
globalVoiceChat=False
proximityChat=False
alwaysNotifyPlayerLeft=True
alwaysNotifyPlayerJoined=True
ServerForceNoHud=False
AllowThirdPersonPlayer=True
ShowMapPlayerLocation=True
EnablePVPGamma=False
DisablePvEGamma=True
ShowFloatingDamageText=True
AllowFlyerCarryPVE=True
XPMultiplier=1.5
TamedDinoDamageMultiplier=1.0
TamedDinoResistanceMultiplier=1.0
AllowRaidDinoFeeding=True
DisableDinoDecayPvE=True
DisableImprintDinoBuff=False
AllowAnyoneBabyImprintCuddle=False
TamingSpeedMultiplier=3.0
HarvestAmountMultiplier=2.0
ResourcesRespawnPeriodMultiplier=0.8
NightTimeSpeedScale=1.5
PvPStructureDecay=False
NewMaxStructuresInRange=25000.0
MaxPlatformSaddleStructureLimit=65535
OverrideStructurePlatformPrevention=True
PvEAllowStructuresAtSupplyDrops=False
DisableStructureDecayPVE=True
PvEStructureDecayDestructionPeriod=0.0
AutoDestroyOldStructuresMultiplier=0.0
ForceAllStructureLocking=False
OnlyAutoDestroyCoreStructures=False
OnlyDecayUnsnappedCoreStructures=False
FastDecayUnsnappedCoreStructures=False
TheMaxStructuresInRange=25000.0
OxygenSwimSpeedStatMultiplier=1.0
PvPDinoDecay=False
AutoDestroyDecayedDinos=False
MaxPersonalTamedDinos=500.0
DestroyUnconnectedWaterPipes=False
AllowCrateSpawnsOnTopOfStructures=True
DayCycleSpeedScale=0.75
DayTimeSpeedScale=0.5
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
PreventUploadSurvivors=False
PreventUploadItems=False
PreventUploadDinos=False
TributeCharacterExpirationSeconds=1200000
TributeItemExpirationSeconds=1200000
TributeDinoExpirationSeconds=1200000
PreventSpawnAnimations=False

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.700000
FOVMultiplier=1.000000
GroundClutterDensity=1.000000
bFilmGrain=False
bMotionBlur=False
bUseDFAO=False
bUseSSAO=True
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
bLocalInventoryShowAllItems=False
bRemoteInventoryShowAllItems=False
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=1
ActiveLingeringWorldTiles=7
ClientNetQuality=3
LastServerSearchType=0
LastDLCTypeSearchType=-1
LastServerSearchHideFull=False
LastServerSearchProtected=False
HideItemTextOverlay=False
bDistanceFieldShadowing=True
LODScalar=1.000000
bToggleToTalk=False
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=False
bChatShowTribeName=True
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bSpectatorManualFloatingNames=False
bSuppressAdminIcon=False
bUseSimpleDistanceMovement=False
bDisableMeleeCameraSwingAnims=False
bHighQualityAnisotropicFiltering=False
bPreventInventoryOpeningSounds=False
bPreventItemCraftingSounds=False
bPreventHitMarkers=False
bPreventCrosshair=False
bPreventColorizedItemNames=False
bHighQualityLODs=False
bExtraLevelStreamingDistance=False
bEnableColorGrading=True
DOFSettingInterpTime=0.000000
bDisableBloom=False
bDisableLightShafts=False
LastPVESearchType=-1
bUseVSync=False
MacroCtrl0=
MacroCtrl1=
MacroCtrl2=
MacroCtrl3=
MacroCtrl4=
MacroCtrl5=
MacroCtrl6=
MacroCtrl7=
MacroCtrl8=
MacroCtrl9=
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3
sg.GroundClutterRadius=10000

[SessionSettings]

[/Script/Engine.GameSession]
MaxPlayers=70

[MultiHome]
MultiHome=False

[MessageOfTheDay]
Message=
Duration=20

[/Game/PrimalEarth/CoreBlueprints/TestGameMode.TestGameMode_C]
bServerGameLogEnabled=True

[Ragnarok]
EnableDevelopmentZones=true

**Comment by cadon** [comment] 2017-08-14 21:41
Found the issue, it will be fixed in the next release. Until then, set the event-multipliers to the same values as the non-event multipliers.

**Comment by cadon** [comment] 2017-08-15 20:36
Fixed in 0.23.15

**Closed by cadon** 2017-08-15 20:36 UTC
Labels: bug
