### ISSUE TITLE
Can't extract stats from 177 Ptera, bred on official theIsland server. 

### ISSUE THREAD

**Issue by BloodlustedPeon** [cadon/ARKStatsExtractor#57] opened 2016-06-08 14:09 UTC
The level comes up red, it's 177. Also whatever I select for the type of creature, Bred/Wild/Tamed it still comes up red.

**Comment by cadon** [comment] 2016-06-08 18:36
Hi, can you post a screenshot of the stats of that ptera?

**Comment by NakramR** [comment] 2016-06-08 18:47
Would you please be so kind as to provide a screenshot of it, please?
Also, verify that there are no "locked" stats.

**Comment by BloodlustedPeon** [comment] 2016-06-08 18:48
http://steamcommunity.com/sharedfiles/filedetails/?id=699935190   is the Ptera, I leveled it up once in melee, also it's kinda funky because of the imprinting. I don't remember the melee being that high

**Comment by BloodlustedPeon** [comment] 2016-06-08 18:50
Maybe i'm typing the things in wrong? I'm not sure to be honest :( I'm fairly new to this app

**Comment by NakramR** [comment] 2016-06-08 18:51
You're not typing things wrong. The problem is the imprinting... We'll come
up with an answer, but it is quite possible we may be unable to determine
(yet) what the values are. We need to verify.

**Comment by BloodlustedPeon** [comment] 2016-06-08 18:53
Ah alright thank you for your help! I'll try it out on different dinos and see if I can get it to work

**Comment by cadon** [comment] 2016-06-08 18:57
for now the tool cannot handle the imprinting bonus. The best is to enter the stats before you start the imprinting process. when you started and got a bonus, the tool will probably fail to extract the stats.

**Comment by cadon** [comment] 2016-07-04 11:00
I'm closing this issue, see #59 for issues regarding imprinting-quality.

**Closed by cadon** 2016-07-04 11:00 UTC
Labels: feature request
