### ISSUE TITLE
Giga nerf issue

### ISSUE THREAD

**Issue by Melemen** [cadon/ARKStatsExtractor#85] opened 2016-07-27 11:20 UTC
The giga level extraction is not working correctly since the nerf done on the June patch, is this going to be adressed?

**Comment by cadon** [comment] 2016-07-27 12:52
Hm, that should work. Can you post a screenshot of the stats of the non-working Giganotosaur?

**Comment by cadon** [comment] 2016-09-26 13:51
I'm closing this issue for now. If the issue is still there, please re-open.

**Closed by cadon** 2016-09-26 13:51 UTC
Labels: stat-issue
