### ISSUE TITLE
Breeding calculator recommending sub-par pairs

### ISSUE THREAD

**Issue by dadas190** [cadon/ARKStatsExtractor#1177] opened 2021-02-14 06:30 UTC
Hello, I have encountered this after years of heavy use of this tool, I was kinda surprised as this never happened to me before, must have stepped on some rare corner case with this one:

https://imgur.com/ixCqy8k

Why does 'YEETUS' have higher breeding score than 238M? 238M has better stamina and the rest of stats are equal, therefore he has better offspring probability no matter what.

**Comment by cadon** [comment] 2021-02-14 10:25
Hi, thanks for this report!
The Breeding Score of `238M` is so low, because the offspring cannot have better top stats than `238M`, so you will not gain better top stats by that pairing.
The issue is that `YEETUS` has such a high score because you will not gain more top stats by that pairing either, the offspring of the first pair will not be better than `238M` regarding the topstats. There was an issue that considered the damage of the potential offspring of the first pair (level 28), which is better than the damage of `238M` (level 27), but because this is not a top stat (the top stat for damage is level 38 by `FETUS`), that shouldn't play a role in this breeding mode. This will be fixed in the next release. You should go for pairings with `FETUS` and `214F` / `214F-2` to merge the weight and damage levels with the top stats for HP, St, Ox and Fo.

**Closed** 2021-02-14 10:43 UTC
Labels: bug
