### ISSUE TITLE
Speed not showing for Turtles in Breeding Plan

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#344] opened 2017-06-14 20:24 UTC
Is there an option to turn this on, I can't find it. More importantly why is it off?

**Comment by cyberangel67** [comment] 2017-06-14 20:29
In fact there is a lot of dinos where speed has been turned off, why is this?

**Comment by cadon** [comment] 2017-06-14 21:23
Hi, the speed can only be extracted if all other stats are known. The turtle has no oxygen (unless you use mods that display that, e.g. super-spy-glass). If a stat-level is not known, it's saved as -1 in the library and usually shown as a greyed out question-mark. So all species that don't show an oxygen stat won't show a speed level as well in the library or breeding planner.
Does this answer the question or is there a thing I oversaw with handling the unknown levels?

**Comment by cyberangel67** [comment] 2017-06-14 22:26
So let me get this right, I can tame a Turtle enter its speed and it now shows as -1

That is so lame, it never used to work this way, so why did you change it?

**Comment by cyberangel67** [comment] 2017-06-14 22:28
And Xbox has no mods, so this is critical for all console users that this get fixed.

**Comment by cadon** [comment] 2017-06-15 09:05
Hm, there was never a way to determine the speed-levels for species that have no oxygen, except if you used a mod that let you see the oxygen-value. That never changed. The speed-levels can only be determined as the difference of the total wild levels and the sum of the other levels, because speed itself doesn't change with wild levels applied.

If this worked differently in a previous version, let me know the version-number and I'll have a look if something related to that was changed.

**Comment by cyberangel67** [comment] 2017-06-15 14:53
I don't think you understand what I am saying, but i don't know what version number it was.

All I know is this.

1) Knock out a turtle, enter its stats it calculates everything correctly.
2) Knock out a Mosa, enter it stats it calculates everything correctly.

Now, you look at the library and they both have -1 for speed, how do you go from calculating them correctly adding them to the library and removing speed?

I asked this question once before, when you could now breed aquatics, because your answer was the exact same answer and I asked you how can you go from calculating mum and dad and have them in the library with stats to not being able to calculate the baby. Your answer has always been, use the super spy glass and on console we don't have that luxury and never will.

So I ask again, how can you go from taming a Turtle, entering it stats, getting it extracted and storing the speed with -1?

**Comment by cyberangel67** [comment] 2017-06-15 18:37
So I have gone back through a lot of your previous versions, where Oxygen used to be able to be entered. I think I know why this is an issue, correct me if I am wrong as I have no screen shots to verify this. But was there a point where oxygen used to be seen on dinos that no longer used it?

Maybe we can partition Jat, Jesse and others to maybe put it back in or even maybe reach out to Jat and ask if there is a way to do it. As this is a brilliant program, but that no makes this program useless for consoles.

**Comment by cyberangel67** [comment] 2017-06-15 18:40
Another though, is there maybe a set value for oxygen for those that don't have it. Anyone on PC able to do determine if the value changes per tame and is a set value?

**Comment by cadon** [comment] 2017-06-15 19:52
The oxygen-stat was always unknown for aquatic creatures. The speed-level for species that don't show the oxygen-stat was never be able to be extracted. All people on official servers (pc and consoles) have no way to know the speed-level of their aquatic creatures, that bit never changed. Only on unofficial servers where there are these mods it is possible to extract the speed-level.

If the stats of a creature with no oxygen is entered in the extractor, the speed-stat is colored green, but the level is always 0, because the level cannot be extracted. When the creature is saved in the library, the level of oxygen and speed are saved internally as -1, because they're both unknown. So even if it seems the speed-level was extracted (marked as green), it is unknown, but there's nothing that can be done about this, so the tool doesn't show it as an error. You can only determine the sum of these two unknown levels, by subtracting the sum of all other wild levels from the torpor-level, but this will not help for breeding.

In ARK there was never a way to see the oxygen-value of creatures that don't use it (except with mods). The one thing I changed according to this, was adding a checkbox in the settings ("Enable oxygen for all species"), for people that use mods like the super-spy-glass. Before this change, the tool didn't accepted an input for the oxygen for the aquatic species at all.

For breeding these species it's not satisfactory to have these two stats not be able to be included in the breeding-planner, but for most people (on the official servers and on unofficial servers without special mods), there's mathematically no way to know the level of the speed.

Regarding the last question: The oxygen is handled as a level like every other level, so it can have different values, dependant on the oxygen-level. The problem is just, it is not displayed. Usually species that don't use oxygen have the default values for the oxygen stat, which is 150 and an increase of 10% (=15) per level. But because the value is not shown, the level is unknown as well.

I hope I answered all questions. If you have more questions or suggestions, on how to handle these unknown levels better, let me know.

**Comment by cyberangel67** [comment] 2017-06-15 21:27
Yes, but I am positive you used to calculate speed for the turtle and Mosa.

Now you are you also saying that, say a turtle, still gets points added into Oxygen even though it doesn't use it?

**Comment by cadon** [comment] 2017-06-15 21:42
> I am positive you used to calculate speed for the turtle and Mosa
I can't remember that, but if the tool did show a number for these, they cannot have been correct. Maybe I did the calculation wrong before I realized the speed cannot be calculated and it did show the sum of both the oxygen- and the speed-level for the speed-level.

Yes, even aquatic species get levels in oxygen, but they're useless. It's the same with the wild-speed-levels: they do increase the total level of the creature, but don't change anything that can be noticed. More wild-levels in speed increase the total level, but don't increase the speed-value. More levels in oxygen in creatures that don't use it, will increase the oxygen-value, but this is not shown, and also not used anyway. If a mod is used to display the oxygen-value of these creatures, one can see that the value does indeed increase, but it has no effect anyway. The only use for displaying that stat (as far as I know) is to use it in the extractor to get the oxygen-level.

**Comment by cyberangel67** [comment] 2017-06-16 02:04
Ok, that makes more sense to me now.

**Comment by cyberangel67** [comment] 2017-06-17 07:31
I have a solution for you

ok going back to basic maths

We know that Hp+St+Ox+Fo+we+dmg+sp = level -1, so we can then do 

Ox = hp+st+fo+we+dmg+sp - (level-1)

We can loop through sp incrementing and check if Ox from there added to the original equation equals level -1

Would that work?

**Comment by cadon** [comment] 2017-06-17 13:17
Hi, unfortunatetly that's not working. It's similar to having one equation with two unknown variables

ox + sp = a

E.g. if a = 10, there are ten different solutions to this (ox = 10, sp = 0; ox = 9, sp = 1; ... ox = 0, sp = 10). None of them can be differentiated from the others to be the correct one.

**Comment by cyberangel67** [comment] 2017-06-17 17:15
That is why you start like this

for(sp=0;sp<=300;sp++) {
   Ox = (20) - 2 + 2 + 2 + 2 + 2 + sp;
   if(ox+ 2 + 2 + 2 + 2 + 2 + sp = 20) then break
}

Or you can do a while loop, if you like.

**Comment by cadon** [comment] 2017-06-17 17:32
The issue is, these two equations are equivalent, i.e. one does not provide different information than the other. The loop you wrote would break on the first iteration, because the Ox in the first loop-line is always set so the equation in the second row is true.

Ox = 20 - (2 + 2+ 2+ 2+2 + 0) = 10;
if ( 10 + 2+ 2+ 2+ 2+ 2 + 0 ==20) break;

or with speed = 6
Ox = 20 - (2 + 2+ 2+ 2+ 2 +6) = 4;
if ( 4 + 2+ 2+ 2+ 2+ 2 + 6 ==20) break;

so all numbers would result in a possible solution.

**Comment by cyberangel67** [comment] 2017-06-17 18:49
Yes but if we follow ordered pairs

ox+sp =20

10+0 = 20 is not correct
4+6 = 20 is also not correct

**Comment by cadon** [comment] 2017-06-20 18:48
Hm, now all the other stats are ommited, i.e. the 2+2+2+2+2, which would solve the equation like
10 + 2+2+2+2+2 = 20 or 4 + 2+2+2+2+2 + 6 = 20.
In the example, ox + sp = 10, only with the addition of the other stats the total level of 20 is formed.

**Closed** 2017-06-24 16:48 UTC
