### ISSUE TITLE
same species separated into pre and post update?

### ISSUE THREAD

**Issue by MiniDrachin** [cadon/ARKStatsExtractor#1101] opened 2020-07-31 12:20 UTC
I tamed a Griffin today (spawned through ini file change) on Valguero.

it now displays separately to all my previous (pre latest update) Griffins.
As you can see it still is in the same species "tab" in my library, the separator just makes it impossible to quickly compare the "new" and the "old" griffins (I suspect the same will happen if I add another Deino - gonna test that later)

So either

1. New Griffins should also get the same "Griffin (Ragnarok)" label as my old Griffins - both are imported through the "last export" function, and I don't see a way to select a species there
2. There should be a way to disable the species seperation within the same species
3. A way to update the old Griffins to only be "Griffins" - possibly with hitting edit and then a way to select the species (I have only a hand full of Griffins, so that shouldn't be a big problem to just export everyone again - but I have a lot of Deinos, and extracting them all again would be a huge pain)

![unknown](https://user-images.githubusercontent.com/17672477/89033381-f62c1400-d336-11ea-8504-7f34ea94c8f8.png)

**Comment by VolatilePulse** [comment] 2020-07-31 18:13
This doesn't appear to be an issue with ASB, but rather the Griffin that was set in the INI file is different from the ones you have previously tamed. This can only be verified through the export files from the new Griffin and one of the previous ones though.

**Comment by MiniDrachin** [comment] 2020-07-31 21:57
1. is there a way to directly see which Griffin came from which export file? Or do I have to search all the files?

2. appearently a restart of ASB solved the problem. Or at least now the Griffin is also in the Griffin (Ragnarok) section

**Comment by VolatilePulse** [comment] 2020-07-31 23:33
The best way to find out is to export the Griffins again and sort file explorer by most recent. 

As far as restarting ASB is concerned, I'm not sure what happened. Maybe @cadon can provide better insight.

**Comment by MiniDrachin** [comment] 2020-08-01 13:50
this is an older export (not updated):

> [Dino Data]
DinoID1=67143192
DinoID2=166874074
DinoClass=/Game/PrimalEarth/Dinos/Griffin/Griffin_Character_BP.Griffin_Character_BP_C
DinoNameTag=Griffin
bIsFemale=False
bNeutered=False
TamerString=Stamm der Drachen
TamedName=Kerra
ImprinterName=
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=1.000000
CharacterLevel=217
DinoImprintingQuality=0.000000
[Colorization]
ColorSet[0]=(R=1.000000,G=0.000000,B=0.000000,A=0.000000)
ColorSet[1]=(R=0.002428,G=0.088656,B=0.124772,A=0.000000)
ColorSet[2]=(R=0.000000,G=0.000000,B=1.000000,A=0.000000)
ColorSet[3]=(R=0.225000,G=0.011337,B=0.005625,A=0.000000)
ColorSet[4]=(R=1.000000,G=1.000000,B=1.000000,A=0.000000)
ColorSet[5]=(R=1.000000,G=1.000000,B=1.000000,A=0.000000)
[Max Character Status Values]
Gesundheit=5037.500000
Ausdauer=691.650024
Benommenheit=20850.500000
Sauerstoff=780.000000
Nahrung=7340.408203
Wasser=100.000000
Temperatur=0.000000
Gewicht=476.000214
Nahkampfschaden=1.637918
Bewegungsgeschwindigkeit=0.365000
Resistenz=0.000000
Handwerkliches Geschick=0.000000
[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0

older Griffin, but exported again/updated
>[Dino Data]
DinoID1=328811740
DinoID2=400130064
DinoClass=/Game/PrimalEarth/Dinos/Griffin/Griffin_Character_BP.Griffin_Character_BP_C
DinoNameTag=Griffin
bIsFemale=False
bNeutered=False
TamerString=Stamm der Drachen
TamedName=Weißfeder
ImprinterName=
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=1.000000
CharacterLevel=260
DinoImprintingQuality=0.000000
[Colorization]
ColorSet[0]=(R=0.300000,G=0.240000,B=0.180000,A=0.000000)
ColorSet[1]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[2]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[3]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[4]=(R=0.635000,G=0.393327,B=0.301625,A=1.000000)
ColorSet[5]=(R=0.850000,G=0.850000,B=0.850000,A=0.000000)
[Max Character Status Values]
Gesundheit=5403.775879
Ausdauer=2112.074951
Benommenheit=20850.500000
Sauerstoff=630.000000
Nahrung=7156.897949
Wasser=100.000000
Temperatur=0.000000
Gewicht=744.799988
Nahkampfschaden=1.344816
Bewegungsgeschwindigkeit=0.365000
Resistenz=0.000000
Handwerkliches Geschick=0.000000
[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0

the new Griffin that was separated prior to a restart:

> [Dino Data]
DinoID1=458222029
DinoID2=420113669
DinoClass=/Game/PrimalEarth/Dinos/Griffin/Griffin_Character_BP.Griffin_Character_BP_C
DinoNameTag=Griffin
bIsFemale=False
bNeutered=False
TamerString=Stamm der Drachen
TamedName=Whitefeather
ImprinterName=
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=1.000000
CharacterLevel=224
DinoImprintingQuality=0.000000
[Colorization]
ColorSet[0]=(R=0.250000,G=0.185219,B=0.133750,A=1.000000)
ColorSet[1]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[2]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[3]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[4]=(R=0.825000,G=0.704920,B=0.668250,A=1.000000)
ColorSet[5]=(R=0.200000,G=0.200000,B=0.200000,A=0.000000)
[Max Character Status Values]
Gesundheit=6035.000000
Ausdauer=596.250000
Benommenheit=21570.500000
Sauerstoff=720.000000
Nahrung=7173.568848
Wasser=100.000000
Temperatur=0.000000
Gewicht=487.200073
Nahkampfschaden=2.173965
Bewegungsgeschwindigkeit=0.365000
Resistenz=0.000000
Handwerkliches Geschick=0.000000
[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0

**Comment by Pingger** [comment] 2020-08-03 18:48
I'm quite sure the issue is related to this commit: https://github.com/cadon/ARKStatsExtractor/commit/e859042a20fba47715277f202a40192cf5ba67d4

**Comment by cadon** [comment] 2020-08-03 20:28
Does this issue persists if you restart ASB? The blueprint paths of the posted export files are identical, so they should be assigned to the same species. The last couple releases have an issue that some species are not initialized completely. I don't see how this could affect the library creatures, but it seems that the first Griffin somehow misses the variant suffix, despite being the same species.

My guess is that is should be resolved after a restart. Maybe you need to set the selected species to a different species before closing. Most likely it's just a display issue and there's no need to re-import the creatures.

**Comment by MiniDrachin** [comment] 2020-08-05 09:50
MiniDrachin commented 5 days ago:
>     2\. appearently a restart of ASB solved the problem. Or at least now the Griffin is also in the Griffin (Ragnarok) section

**Closed** 2020-08-13 12:22 UTC
