### ISSUE TITLE
Does it run on MacOS?

### ISSUE THREAD

**Issue by TobyPlayz5** [cadon/ARKStatsExtractor#952] opened 2019-09-16 04:36 UTC
ARKStatsExtractor (Smart Breeding) isn't available to use or open on a MacBook, considering that I don't have the money to buy a PC, is it possible for you to create a version of ARKStatsExtractor that can be used on a MacBook, I don't want to download any Wine Extractors, so please consider creating a version that is available for Mac?

**Comment by cadon** [comment] 2019-09-16 08:37
Maybe it works with [mono](http://www.mono-project.com). Currently there are no plans for a dedicated MacOS version.

(Duplicate of #193)

**Closed** 2020-03-21 19:29 UTC
Labels: question
