### ISSUE TITLE
Tek Raptor and Tek Rex don't extract correct Wild Levels

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#851] opened 2018-12-13 02:37 UTC
As per the previous Ticket, the Tek Rex and Tek Raptor don't calculate the Wild Levels correctly.

The following images show a casteroid, that extracts right and the other Tek Dinos as calculating the Wild Levels correctly.

![capture](https://user-images.githubusercontent.com/1366816/49911857-1b5add00-fedc-11e8-9be5-6b1e23213a84.PNG)
![capture1](https://user-images.githubusercontent.com/1366816/49911864-1e55cd80-fedc-11e8-9afd-d2481223e6e7.PNG)
![capture2](https://user-images.githubusercontent.com/1366816/49911867-20b82780-fedc-11e8-8596-67c30cb49a93.PNG)
![capture3](https://user-images.githubusercontent.com/1366816/49911870-2281eb00-fedc-11e8-9880-4ea0c8af8835.PNG)
![capture4](https://user-images.githubusercontent.com/1366816/49911872-27469f00-fedc-11e8-9191-14e059ee6f29.PNG)

**Comment by cyberangel67** [comment] 2018-12-13 02:38
![capture5](https://user-images.githubusercontent.com/1366816/49911926-5ceb8800-fedc-11e8-8f52-ca741901c109.PNG)

**Comment by cyberangel67** [comment] 2018-12-13 02:44
Actually I take that back...

All Tek Dino's if tamed at the highest possible level, don't calculate right.
![capture](https://user-images.githubusercontent.com/1366816/49912144-40038480-fedd-11e8-8a6c-d9351890dee0.PNG)

**Comment by VolatilePulse** [comment] 2018-12-13 02:49
I have replicated your issue in game. All Tek creatures spawned with the `GMSummon` command instantly have 20% added to their base levels.

You can view the included screenshots for further proof. Pay particular attention to the spawn command used and the creatures' resulting Post Tamed Level: 
![image](https://user-images.githubusercontent.com/6995232/49912045-c4f78b00-fe56-11e8-81cf-c34350d6013d.png)
![image](https://user-images.githubusercontent.com/6995232/49912196-58c95700-fe57-11e8-996d-7e8f89da9f14.png)
![image](https://user-images.githubusercontent.com/6995232/49912223-7d253380-fe57-11e8-9ac8-dd35e54bb9eb.png)
![image](https://user-images.githubusercontent.com/6995232/49912250-91693080-fe57-11e8-9fc2-043ca3f87249.png)

Unless you're going to provide further information as to why you think ASB is incorrectly extracting the TamedLevel, please stop opening duplicate issues or further action will be taken.

**Comment by VolatilePulse** [comment] 2018-12-13 02:49
Duplicate of #850

**Closed by VolatilePulse** 2018-12-13 02:49 UTC
