### ISSUE TITLE
Creature ID & Editing Issue

### ISSUE THREAD

**Issue by PreshusRoze** [cadon/ARKStatsExtractor#763] opened 2018-08-23 19:57 UTC
When I open a saved dino (to add to the notes now that I know what the mutation point has affected) I see that the ID I had (previously) manually entered, is listed as "0".
![id editissue](https://user-images.githubusercontent.com/36016275/44548805-200d4280-a6ed-11e8-9b52-295438e35697.png)

-- [And BTW: When tapping TAB to go down the information lines, it does NOT select/land on the ID section]
So I re-enter the ID, add my note about the mutations and get the following error when I try to "Save Changes".
-- The error message indicates that it DID SAVE the ID information (somewhere) when I manually entered it initially. It's just not DISPLAYING that it was loaded or saved.
![id editing issue](https://user-images.githubusercontent.com/36016275/44548782-0ec43600-a6ed-11e8-9d66-f3fd1b25129b.png)

-- When I use the SAVE ICON at the top I do not get the error - BUT, it does NOT save the notes/edits I've added either. [Library information has not changed]
-- Also, IF there is a new column that is supposed to display the ID (yes please)- it's not showing or I can't get it to uncover to display. 
-- And IF the ID information is supposed to show on the left side (like NOTE does) when you highlight the dino in question in Library (which would be AWESOME if it would) - it's not displaying either.
-- If the only way to see the ID is going into EDIT mode, that's not very practical and very time consuming. Please look into adding the ability to view the ID while in LIBRARY tab, like you do all other information.

![noidinfo](https://user-images.githubusercontent.com/36016275/44548817-2b606e00-a6ed-11e8-851f-6e1b1e0e40b0.png)

**Comment by VolatilePulse** [comment] 2018-08-23 20:01
I think the implementation was a it rushed here, but the developer is good at addressing issues and will work on a fix once he's available again. Most of these should be easy enough to fix but might take a couple of weeks. Do you happen to have the export file for this mammoth? I wanted to do some research on the creature ID generator to see if there is a potential fix for your other issue you submitted.

**Comment by PreshusRoze** [comment] 2018-08-23 20:12
Yes I still have the exported file.
I know the developer will be available to work the issues in a week or so. I'm not in a hurry but wanted them to be aware of the issues so far experienced by me with the update.
Even if the implementation was rushed, I'm LOVING that it's even being implemented! That way I can use my NOTE section for the other info I want to use it for, and have a more narrow column. lol
[[Take note of my library screenshot above. I have been noting the last 7 of each ID in NOTE and PRAY I never have another dino with the same last 7 - lol]]

**Comment by cadon** [comment] 2018-08-23 20:39
Hi, thanks for the feedback. I found some bugs and released 0.28.9.1, again cobbled together hurridly. No garantuee it will not break everything, so a backup of the library is advised again.

**Comment by PreshusRoze** [comment] 2018-08-23 20:51
**duct taping my tribbles before updating** Gotcha!

**Comment by Worldgate** [comment] 2018-09-02 19:58
Im glad were finally using the ark-id for dinos, i had requested it a while ago. :)

**Comment by coldino** [comment] 2018-09-03 09:46
Although using the Ark ID would have been ideal, we've discovered that it's not going to be possible moving forward. Ark IDs are simply not unique enough. IDs really *have* to be unique or bad things happen in a database-like app such as ASB.

Some background...
Internally to Ark, creatures are identified by two separate 32-bit integer fields called DinoID1 and DinoID2.

ASB is currently importing these by combining the two into a single bigger integer using bit manipulation methods. This results in a number that will can never be obtained from any two other DinoID1 and DinoID2 pairs, and so is as unique as possible, given the inputs.

Ark, on the other hand, combines these two fields by simply concatenating the *strings* of DinoID1 and DinoID2. This is a terrible method and will result in the same output for multiple different inputs. Consider the simple example of DinoID1 as `1` and DinoID2 as `2345`, resulting in an Ark ID of `12345`. This would produce the same result as `12` + `345`, `123` + `45` as well as `1234`+`5`.

This poor method of producing IDs doesn't really matter for display purposes, or even for the naming of the .ini dino export files, but it simply cannot be used internally to ASB or it will result in data loss or corruption.

As discussed on Discord, we feel it would be nice to have the Ark ID available as a separate plain text field of each creature. It can be filled in automatically upon import, and can be edited by the user as much as they like. But it should never be for creature identification.

**Comment by cadon** [comment] 2018-11-03 16:36
The issue is resolved in the latest release.

**Closed by cadon** 2018-11-03 16:36 UTC
Labels: bug
