### ISSUE TITLE
Unused color regions have falsely color id 41 assigned. Magmasaurs colors have swapped region lables.

### ISSUE THREAD

**Issue by Caldar** [cadon/ARKStatsExtractor#1057] opened 2020-04-04 22:26 UTC
I'm not sure the exact issue but it seems like the colors reported for Tips and Gradient are reversed. I think this might also be listed wrong on the wiki.

I have bred multiple magmasaurs and the colors listed for these two regions seem to be swapped.

I imagine that the colors are right but the zone labels are wrong for both the wiki and the app.

Also, an old bug seems to have come back. All of the color regions for all the dinos that I am importing that are not used by that dino are being filled with color #41. This just started happening in the last version or two.

**Comment by cadon** [comment] 2020-04-04 23:12
Hi,
do you mean that a creature has the color-id 41 for regions that are not at all used for that species?

**Comment by Caldar** [comment] 2020-04-04 23:14
Yes, I think you responded to me in Discord so you can probably close this ticket unless you want the note about how there is an issue on someones end about the Magmasaurs.

**Comment by ShadowRune** [comment] 2020-08-31 03:04
When looking in our library, our (C2) and (C5) should be flipped.
The tips and gradient are reversed by labeling.

**Comment by ShadowRune** [comment] 2020-09-06 00:31
I don't know which is incorrect, the labeling or the region identification. but to best explain a last time (sorry)
**C2 says it is for gradient when in the smart breeder image and in the game it shows as Tips
C5 says it is for tips when in the smart breeder image and in the game it shows as Gradient**
Thank you for all you have done, you are an inspiration!

**Comment by cadon** [comment] 2020-09-06 10:04
Thanks for the report. This will be fixed soon.
(duplicate of #1117)

**Closed by cadon** 2020-09-06 10:04 UTC
Labels: Data incorrect, bug
