### ISSUE TITLE
Timezones and filesync

### ISSUE THREAD

**Issue by darthginger** [cadon/ARKStatsExtractor#257] opened 2017-04-13 17:04 UTC
Saving local timezones in the database is problematic when using a cloud service like Seafile and Autosave/Autoload Collection file with people from different timezones. When a person from another timezone saves the database, all times get updated to their local timezone, which can lead to conflicts with certain file sync tools like Seafile.

**Comment by cadon** [comment] 2017-04-28 16:37
Hi, do you mean the times like "Tamed at" and/or the timers in the tool, or the date of the library-file itself?

**Comment by darthginger** [comment] 2017-04-28 17:19
in the library file itself for example: `<domesticatedAt>2017-01-12T18:50:00.2649683+01:00</domesticatedAt>` the timezone "+01:00" is obviously different for people from different timezones and cause a lot of changes in the file with autoload/autosave enabled

**Comment by cadon** [comment] 2017-04-28 17:54
Ah, I see. Thanks for the feedback. Is the timestamp itself changed as well, e.g.
`<domesticatedAt>2017-01-12T18:50:00.2649683+01:00</domesticatedAt>` is not only changed to e.g.
`<domesticatedAt>2017-01-12T17:50:00.2649683+02:00</domesticatedAt>`, but to a time that is different like e.g.
`<domesticatedAt>2017-01-12T18:50:00.2649683+02:00</domesticatedAt>`?

**Comment by darthginger** [comment] 2017-04-28 18:04
from `<domesticatedAt>2017-01-12T18:50:00.2649683+01:00</domesticatedAt>`
to `<domesticatedAt>2017-01-12T19:50:00.2649683+02:00</domesticatedAt>`

**Comment by cadon** [comment] 2017-04-28 18:24
Ah, my bad. What you wrote is what I would expect. It's the same time in two different time-zones.

So the issue is, a file is saved with your time-zone-times, synced to the tribe mate in another time-zone, which causes the timestamps to be rewritten and saved and then the file is synced again, despite no real change was made?

**Comment by darthginger** [comment] 2017-04-28 18:44
There is no "ping pong" if thats what you mean. Seafile just makes a copy with a "conflict" mark.

**Comment by cadon** [comment] 2017-04-28 19:19
Ah, good to know, that's what I feared.

The conflict-mark probably means the file was changed on both sides and seafile doesn't know how to merge the files. This issue looks more like that seafile doesn't sync the files fast enough, or that changes were made on both sides at the same time. A file-sync should only be triggered if the file changes, so as long as no new creature or timer is added or edited, there should be no sync. The new timestamps should only be saved to the file if there was a real change (there might be bugs that trigger a save when there is no change), so a conflict should only appear if two real changes are made.

Is there a reason you think the timestamps are the reason for the conflicts? Does this only happen with people from other timezones?

Can you, for testing purposes, ask the people from the other time-zone to change the time-zone on their machine to yours and see if the issue persists?

**Comment by darthginger** [comment] 2017-04-28 19:52
> This issue looks more like that seafile doesn't sync the files fast enough, or that changes were made on both sides at the same time.
Yes this happens too.

> Is there a reason you think the timestamps are the reason for the conflicts?
Not directly i think. The reason is probably two changes at the same time.

> Does this only happen with people from other timezones?
The conflicts? Yes for the same reason as above.

**Comment by Freso** [comment] 2018-02-11 11:39
Maybe just always save times in UTC/Zulu time/+0000 and only use local timezone for display, instead of converting timezones all the time? In addition to sync issues (which may or may not be alleviated tweaking the sync solution), the file constantly changing means it will cause a lot of unneeded I/O (network and storage), and it will be much harder to get useful information from "file last modified" etc. filesystem metadata.

**Comment by cadon** [comment] 2020-03-19 22:18
That issue was resolved in the meantime. Timestamps are now always saved in UTC.

**Closed by cadon** 2020-03-19 22:18 UTC
Labels: bug
