### ISSUE TITLE
Breeding Plan Issue

### ISSUE THREAD

**Issue by Kkalexx** [cadon/ARKStatsExtractor#667] opened 2018-04-14 20:26 UTC
In the Breeding Mod;
Switching between Top Stats Cn/Lc and High Stats doesn't seem to work properly.

**Comment by kohonac** [comment] 2018-04-15 01:26
more information with some screenshots of your ASB will help the developer if there is a problem and if not may allow someone to help you if its working as intended.

**Comment by Kkalexx** [comment] 2018-04-15 20:14
I will try to do my best to explain as my english is not perfect.

The breeding planner do not update when I cycle between **Top Stats Cn / Top Stats Lc / High Stats** using the radio buttons. When I start ASB and select the Breeding Plan tab, the Breeding-Scores from High Stats are shown and when I try to use the radio buttons nothing happens until I select **Top Stats Cn**. At this very moment, it's is impossible to update the planner (Breeding-Score) when I select any of the 3 radio buttons. 

I loaded the same library back into ASB v0.27.1 and it's working like a charm.

I didn't tried it with v0.27.2.

Let me know if you need more info.

**Comment by cadon** [comment] 2018-04-15 21:08
Thanks for the report. It's fixed now in 0.27.6.

**Closed by cadon** 2018-04-15 21:08 UTC
Labels: bug
