### ISSUE TITLE
General issues extracting food and damage

### ISSUE THREAD

**Issue by EveTater** [cadon/ARKStatsExtractor#62] opened 2016-06-14 14:17 UTC
Hey, so since the last update it was working fine for me for a few days. Upon entering some new dinos I got, however, they seem to be having issues with food and damage. It is not every dino that this happens with (for instance, some of the new pters work while others do not) and it happens across different species. The stats are always triple checked and entered correctly, the since taming checkbox does nothing, the max levels are set correctly, the multipliers are set correctly, and the other stats extracting are always fine. I'm not sure what could be the cause of this.

Also, another oddity is sometimes after extracting into the library at a set level it will set the LW to some seemingly random number that is not accurate, however other times it puts the correct number. This isn't really a big deal but it's annoying.

**Comment by cadon** [comment] 2016-06-15 17:12
Hi, can you post a screenshot of a creature that does not work along with the multipliers of the server? If the creatures have an imprinting-bonus, the tool cannot handle that yet.

Also, can you post the stats of creature that gives a wrong LW in the library?

**Comment by EveTater** [comment] 2016-06-16 09:37
I cannot get the original wild stats (or the after tame bonus alone either) as I'm sure one of my tribe mates has put levels in by now, however the extractor should be able to assign bonus levels anyway. There is no imprinting bonus, all of the dinos have been tamed not bread so far, and it's an official pve server so the base multipliers are on. As for a dino that has this stat issue in the extractor: 
![ark extractor issue data](https://cloud.githubusercontent.com/assets/19828545/16112095/d7b07a72-3383-11e6-86f2-247a5702b6c4.png)

For the LW thing
![ark extractor issue data 2](https://cloud.githubusercontent.com/assets/19828545/16112182/3366b49e-3384-11e6-8032-a806d14c2b23.png)
The highlighted one in the library is the one being looked at in ark, although as you can see in the library some of the others do it as well (official center server max wild is 150, the issue is with the ones that have 256 which is only one other pter in the pick, but other dinos do this as well)

**Comment by cadon** [comment] 2016-06-16 12:15
Hi, there was apparently an issue with the extracting. I guess you forgot to check "Since taming no Server-Restart". The torpor of that creature is at level 360, with a taming effectiveness of 83.1% the wild level has to be 256.

The reason for that checkbox is a bug in the game, that displays too high torpor-values right after taming. If you see that the wild-level is way too high, that's probably the cause.

**Comment by EveTater** [comment] 2016-06-16 13:43
It has had a restart before I put it in though

**Comment by cadon** [comment] 2016-06-16 13:48
Hm, that's interesting. Seems then the torpor-bug doesn't get solved by a restart, but something else. Maybe it's just a specific amount of time that the values are recalculated.

**Comment by cyberangel67** [comment] 2016-06-29 04:11
If it helps I just tamed this Casteroid on The Island Official server and the program is telling me that the LW was 122, when it was actually a 120.
![capture](https://cloud.githubusercontent.com/assets/1366816/16440250/639f8e7c-3e03-11e6-8998-575f217866fd.PNG)

**Comment by cadon** [comment] 2016-06-29 10:28
Thanks! That's strange, these stats are not possible that way. Maybe the extraction was wrong? The wildlevels add up to 176, so the total level should be 177, but it's 175. Can you send a screenshot of the inventory with the stats of that creature?

**Comment by cyberangel67** [comment] 2016-06-29 12:16
Yeah they are the stats, except torpor. Since this was taken the inventory is different and the stats are different, as I have put some into weight and dmg.

![xbox 27_06_2016 11_51_21 am](https://cloud.githubusercontent.com/assets/1366816/16451521/f3796868-3e46-11e6-9493-d85f31b1bec3.png)

**Comment by cadon** [comment] 2016-06-29 16:50
Finally solved that one. The source of the problem here is that the melee-damage was nerfed recently, so the extractor always got wrong numbers for the melee-damage-levels if it uses the current numbers. The correct numbers for that beaver are: Melee-damage 18 Level, Taming-effectiveness: 97.5%. With these numbers the wild-level is 120 then.

Either you edit your creature in the editor, or you extract it with the current (leveled) values again.

**Comment by kurai-ookami** [comment] 2016-09-30 12:30
This issue seems like it still exists for some creatures. This Kairuku has never been leveled up and the torpor has dropped from it's initial taming (also server has restarted since taming. But it still reads as something is wrong when pulling stats.
![example](https://cloud.githubusercontent.com/assets/1554026/18991677/e7c8eff4-86e7-11e6-995a-442170d34172.jpg)

**Comment by cadon** [comment] 2016-09-30 18:49
Hi, you can try to level up damage one level (I guess that's the stat making issues, the food just depends on the taming effectiveness as well and gets invalid). The game recalculates the value after a levelup, so that would probably solve it, if the issue is in an outdated value that is displayed.

**Comment by cadon** [comment] 2017-07-02 11:31
The torpor-bug is resolved ingame, this issue should be solved as well.

**Closed by cadon** 2017-07-02 11:31 UTC
Labels: bug, stat-issue
