### ISSUE TITLE
Imprint problem carbonemys

### ISSUE THREAD

**Issue by Konys1** [cadon/ARKStatsExtractor#568] opened 2017-12-25 17:30 UTC
Hey, Carbonemys now only need 2 imprint to get the 100%, I got 1 imprint on one and tried to set it at 50%  but it says error and automatically sets the imprint to 34.56%.

I guess it is not updated ? If so what settings should I type in BabyCuddleIntervalMultiplier (assuming it is the one I have to change)

**Comment by cadon** [comment] 2017-12-27 11:29
Hi, the imprinting changed, the tool needs to be updated, I can work on this in january. I'm closing this issue as being a duplicate of #559. There a user posted some numbers for the cuddleinterval, maybe this works for you, too.

**Closed by cadon** 2017-12-27 11:29 UTC
Labels: stat-issue

**Comment by Konys1** [comment] 2017-12-28 05:58
I think I didn't type the correct values, first time using it.
