### ISSUE TITLE
cant add carbonemys

### ISSUE THREAD

**Issue by henrik123098** [cadon/ARKStatsExtractor#230] opened 2017-03-28 18:22 UTC
carbonemys have no oxygen and that is why the program can extract the stats from the ark

**Comment by cadon** [comment] 2017-03-28 20:34
Just uncheck "Enable oxygen for all species" in the settings.

**Comment by henrik123098** [comment] 2017-03-29 15:04
![2017-03-29](https://cloud.githubusercontent.com/assets/26748382/24461537/ae556688-14a1-11e7-9525-b26a25ac8127.png)
![2017-03-29 1](https://cloud.githubusercontent.com/assets/26748382/24461549/b9326f38-14a1-11e7-8464-19098de64f31.png)
![2017-03-29 2](https://cloud.githubusercontent.com/assets/26748382/24461552/bbb22ad2-14a1-11e7-80f0-eef00f41def6.png)

**Comment by henrik123098** [comment] 2017-03-29 17:48
it is still not working

**Comment by cadon** [comment] 2017-03-29 18:50
Hm, try to check the checkbox, click ok, then open the settings and uncheck it again. If you scroll through the specieslist with your moure-wheel, does the oxygen-stat gets enabled and disabled depending on the species?

**Comment by henrik123098** [comment] 2017-03-29 19:49
no it dosent

**Comment by henrik123098** [comment] 2017-03-29 19:55
okay i fixed it i had to check the box and the press ok the save and close the program and restart it and then uncheck it again and the save and close and the start it up again and now it works :D 

thx for the help and by the way it a very cool program you have made it realy helps a lot :D

**Comment by henrik123098** [comment] 2017-03-29 19:59
but one thing have you made a video of the program where you explain how it works cuz there is still something i do not yet understand how works, like the mutations and pedigree.

**Comment by henrik123098** [comment] 2017-03-29 20:54
i also have this problem
![2017-03-29 3](https://cloud.githubusercontent.com/assets/26748382/24476164/a35abfd6-14d2-11e7-9a73-803b4fc2d295.png)
![2017-03-29 4](https://cloud.githubusercontent.com/assets/26748382/24476187/ae1fe18a-14d2-11e7-8d4b-56b05ffae177.png)

**Comment by cadon** [comment] 2017-03-29 23:06
Imprinted creatures sometimes doesn't work because the game doesn't update the stat-values immediately, but only after a day or so.

For the general use I recommend https://www.youtube.com/watch?v=zOYvKhLAHL4, for the mutations watch https://www.youtube.com/watch?v=MsWqy24G4-A.

**Comment by henrik123098** [comment] 2017-03-30 12:14
okay ty but this spino have been fully grown for over a month

**Comment by cadon** [comment] 2017-03-30 18:58
Hehe, found the issue. The game shows "601.2" instead of the "501.2" you used in the extractor. Keep in mind, the OCR is not perfect and does mistakes like this.

**Comment by henrik123098** [comment] 2017-03-31 06:40
yes i know but the program won't let me chance the number from 501,2  to 601,2 it just keeps being red

**Comment by cadon** [comment] 2017-03-31 08:06
Wow, that needs an explanation in more detail. You can't click on the input with the "501.2" in it and type "601,2" to change that value?

If that's the case, can you post the operating system you're using and if possible the installed .NET-version (should be visible in the installed software-list)?

**Comment by henrik123098** [comment] 2017-03-31 08:25
i can change the value but it wont recalculate it just go back to the 501,2 value again for some reason

**Comment by cadon** [comment] 2017-03-31 19:08
Just to be sure, there are two buttons: "Read values from ARK window" does read the values from the game. As said, this is not always correct and may need manual corrections by the user. To extract the levels, you have to click on "Extract Level Distribution". If you correct a value and then click on "Read values from ARK window", it will try to read the values again from the ark-window and overwrite the values in the input-boxes, likely making the same mistakes.

So after you did a correction, don't click on "Read Values from ARK window", but directly on the extract-button.

**Comment by cadon** [comment] 2017-04-02 18:42
Hi, I hope the issue is resolved, so I'm closing this for now. If you need further assistance, just reopen it.

**Closed by cadon** 2017-04-02 18:42 UTC
Labels: question
