### ISSUE TITLE
Allosaurus - 214

### ISSUE THREAD

**Issue by alexgtech** [cadon/ARKStatsExtractor#133] opened 2017-01-10 14:46 UTC
It's unable to determine the stats on my 214, here are the screenshots:
http://imgur.com/a/dOj7r
http://imgur.com/a/kek5X

**Comment by cadon** [comment] 2017-01-10 19:46
Hi, are you on an unofficial server with modified multipliers?

**Comment by alexgtech** [comment] 2017-01-10 23:12
Official server: NA-ScorchedEarth787

**Comment by jasin** [comment] 2017-01-11 01:51
I had issues with this as well, read the warning in the app and verify that you are not in the process of imprinting and that the bred dino is fully matured and a server reset has happened. then double check the extraction fails. Else, grab the stats before you imprint

Eventually my Bred Pteranodon was extracted correctly and it wasn't until the maturation process was finished.

**Comment by cadon** [comment] 2017-01-11 10:07
Yes, the issue is most likely the one @jasin described, thanks for pointing that out!

The problem is, that the game doesn't always increase all stat-values, it sometimes "forgets" some stats. In your case it seems it only increased the health-stat, so that could be extracted and not the other stats (stamina and oxygen are never increased, so they work regardless). Solutions to get the correct stat-values can be: wait for a server-restart, going out of render-distance, restart your game. In most cases it'll work if you try it the next day or if the creature is fully imprinted.

**Comment by cadon** [comment] 2017-01-27 22:36
I'll close this for now, I guess the issue is resolved. If not, feel free to reopen this one or open a new issue.

**Closed by cadon** 2017-01-27 22:36 UTC
Labels: stat-issue
