### ISSUE TITLE
Dino's Don't Import (Sometimes)

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#962] opened 2019-09-26 13:28 UTC
For whatever reason dino's will refuse to import.  I can get around it by importing several, including the one who doesn't want to save into the breeder, into a new database and then 'load and add' into the old database.  Is there a way to show a debug console so i can see whats going on and report it?

**Comment by VolatilePulse** [comment] 2019-09-26 17:32
Typically, the only reason a Dino won't import is if it is already in your library. Other potential issues include ASB being unable to match the creature's species blueprint due to a mod not being loaded. I don't think it's the latter, but may be the prior.

Anyway you can provide your library file along with any export files that are causing this? The program doesn't have any built in debugging, but you could attempt debugging in Visual Code to track down the issue.

**Comment by VolatilePulse** [comment] 2020-04-10 04:02
Closing due to age and inability to reproduce and lack of a followup.

If the issue has persisted this long, please reopen this issue or start a new issue and help us troubleshoot the issue by providing any relevant files.

**Closed by VolatilePulse** 2020-04-10 04:02 UTC
Labels: invalid, question
